src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pays;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $CP;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Rue;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Status;

    /**
     * @ORM\Column(type="float")
     */
    private $MTotal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tel;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): self
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getCP(): ?string
    {
        return $this->CP;
    }

    public function setCP(string $CP): self
    {
        $this->CP = $CP;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->Rue;
    }

    public function setRue(string $Rue): self
    {
        $this->Rue = $Rue;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->Status;
    }

    public function setStatus(bool $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getMTotal(): ?float
    {
        return $this->MTotal;
    }

    public function setMTotal(float $MTotal): self
    {
        $this->MTotal = $MTotal;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getCreatedAt(): ?string
    {
        return date_format($this->created_at, "j/m/o - H:i:s");
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/Panier.php
<?php

namespace App\Entity;

use App\Repository\PanierRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=PanierRepository::class)
 */
class Panier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    public function getId(): ?int
    {
        return $this->id;
    }


}

src/Form/PanierType.php
<?php

namespace App\Form;

use App\Entity\Panier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PanierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Panier::class,
        ]);
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Entity\CommandePlants;
use App\Entity\User;
use App\Entity\Panier;
use App\Entity\Plants;
use App\Form\PanierType;
use App\Entity\PanierPlants;
use App\Repository\PanierRepository;
use App\Repository\PlantsRepository;
use App\Repository\PanierPlantsRepository;
use App\Repository\UserProfilRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/panier")
 */
class PanierController extends AbstractController
{
    /**
     * @Route("/", name="panier", methods={"GET"})
     */
    public function index(PanierRepository $panierRepository, PlantsRepository $PlantsRepository, PanierPlantsRepository $PanierPlantsRepository,  UserInterface $user, UserProfilRepository $userProfilRepository): Response
    {
        $PanierPlants = $PanierPlantsRepository->FindByPanier($user->getPanier());
        $count = 0;
        $Mtotal = 0;
        while ($count != count($PanierPlants))
        {
            $Mtotal = $Mtotal + ($PanierPlants[$count]->getPlants()->getPrice() * $PanierPlants[$count]->getQt() );

            $count += 1;
            
        }

        
        return $this->render('panier/index.html.twig', [
            'PanierPlants' => $PanierPlantsRepository->FindByPanier($user->getPanier()),
            'UserProfil' => $userProfilRepository->FindAdr($user),
            'Mtotal' => $Mtotal
        ]);
    }



    /**
     * @Route("/{id}", name="panier.delete", methods={"DELETE"})
     */
    public function delete(Request $request, PanierPlantsRepository $PanierPlantsRepository, Plants $plants, UserInterface $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$plants->getID(), $request->request->get('_token'))) {
            $PanierPlants = $PanierPlantsRepository->FindByPlants($plants, $user->getPanier());
            $PanierPlantsRepository->removeByPlants($plants->getID());
        }

        return $this->redirectToRoute('panier', [], Response::HTTP_SEE_OTHER);
    }


    /**
     * @Route("/confirm", name="panier.confirm", methods={"GET"})
     */
    public function confirm(UserInterface $user, UserProfilRepository $userProfilRepository, PanierPlantsRepository $panierPlantsRepository)
    {
        $PanierPlants = $panierPlantsRepository->FindByPanier($user->getPanier());
            $count = 0;
            $Mtotal = 0;
            $NBplante = 0;
            while ($count != count($PanierPlants))
            {
                $Mtotal = $Mtotal + ($PanierPlants[$count]->getPlants()->getPrice() * $PanierPlants[$count]->getQt() );
                $NBplante = $NBplante + ($PanierPlants[$count]->getQt());
                $count += 1;
                
            }
        return $this->render('panier/confirm.html.twig', [
            'UserProfil' => $userProfilRepository->FindAdr($user),
            'Mtotal' => $Mtotal,
            'NBarticle' => $count,
            'NBplante' => $NBplante

        ]);
    }

    /**
     * @Route("/confirm/add", name="panier.confirm.add", methods={"CREATE"})
     */
    public function create(Request $request,UserInterface $user, PanierPlantsRepository $panierPlantsRepository)
    {

        if($this->isCsrfTokenValid('create' . $user->getId(), $request->request->Get('_token'))) {
            $PanierPlants = $panierPlantsRepository->FindByPanier($user->getPanier());
            $count = 0;
            $Mtotal = 0;
            while ($count != count($PanierPlants))
            {
                $Mtotal = $Mtotal + ($PanierPlants[$count]->getPlants()->getPrice() * $PanierPlants[$count]->getQt() );
                $count += 1;
            }

            if ($PanierPlants != NULL)
            {
            $commande = New Commande();
            $commande->setUser($user);
            $commande->setNom($request->request->get('last_name'));
            $commande->setPrenom($request->request->get('first_name'));
            $commande->setMail($request->request->get('mail'));
            $commande->setTel($request->request->get('phone'));
            $commande->setVille($request->request->get('city'));
            $commande->setPays($request->request->get('country'));
            $commande->setCP($request->request->get('CP'));
            $commande->setRue($request->request->get('street'));
            $commande->setStatus(false);
            $commande->setMTotal($Mtotal);

            $em = $this->getDoctrine()->getManager();
            $em->persist($commande);
            $em->flush();


            

            
            $count = 0;
            while ($count != count($PanierPlants))
            {
                $CommandePlants = new CommandePlants();
                $CommandePlants->setCommande($commande);
                $CommandePlants->setQuantity($PanierPlants[$count]->getQt());
                $CommandePlants->setTitle($PanierPlants[$count]->getPlants()->getTitle());
                $CommandePlants->setPrice($PanierPlants[$count]->getPlants()->getPrice());
                $CommandePlants->setPlid($PanierPlants[$count]->getPlants()->getId());

                $em->persist($CommandePlants);
                $em->flush();

                $count += 1;
            }

            $panierPlantsRepository->removeByUser($user);
            }
        }
        return $this->redirectToRoute('panier');
    }

    /**
     * @Route("/catalogue/{id}", name="catalogue.add", methods={"ADD"})
     * @return Response
     */
    public function add(Plants $plants, Request $request, Security $security, PanierPlantsRepository $panierPlantsRepository) : Response
    {

        
        if($this->isCsrfTokenValid('add' . $plants->getId(), $request->request->Get('_token'))) {
            $em = $this->getDoctrine()->getManager();
           
            $user = New User();
            $user = $security->getUser();

            $PanierPlants = new PanierPlants();

            $result = $panierPlantsRepository->FindByPlants($plants, $user->getPanier());
           
            if ($result == NULL)
            {
                
                $PanierPlants->setPlants($plants);
                $PanierPlants->setPanier($user->getPanier());
                $PanierPlants->setQt($request->request->Get('_quantity'));
                $em->persist($PanierPlants);
            
           
            }else{
                $PanierPlants = $panierPlantsRepository->FindByPlants($plants, $user->getPanier());
                if (($PanierPlants[0]->getQt() + $request->request->Get('_quantity') <= ($plants->getQuantity())))
                {
                    $PanierPlants = $panierPlantsRepository->FindByPlants($plants, $user->getPanier());
                    $PanierPlants[0]->setQt($PanierPlants[0]->getQt() + $request->request->Get('_quantity'));
                    $em->persist($PanierPlants[0]);
                }
                else
                {
                    $PanierPlants = $panierPlantsRepository->FindByPlants($plants, $user->getPanier());
                    $PanierPlants[0]->setQt($plants->getQuantity());
                    $em->persist($PanierPlants[0]);
                }
                
                
            }
            
            
                
            
            
        }
            $em->flush();
            
    
           
           
            
        

        return $this->redirectToRoute('panier');
        
       
    }
}

templates/panier/confirm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande en cours d'achat{% endblock %}

{% block body %}
<style>
  button[data-acc-step]:not(.open) { background: #f2f2f2;  }
</style>


<div class="container mt-5">
<form method="POST" action="{{ path('panier.confirm.add') }}" >
    <input type="hidden" name="_method" value="CREATE">
    <input type="hidden" name="_token" value="{{ csrf_token('create' ~ app.user) }}">
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" data-acc-step>
      <span class="badge rounded-pill text-bg-primary " data-acc-step>1</span> <h5 class="ms-3 mb-0">Information</h5>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
         <div class="container p-2">
          {% for UserProfil in UserProfil %}
      <div class="row justify-content-md-center p-2">
        <div class="col-md-4">Prénom<input type="text" name="first_name" class="form-control" aria-label="Prénom" value="{{ UserProfil.prenom }}" required></div>
        <div class="col-md-4">Nom<input type="text" name="last_name" class="form-control" aria-label="Nom" value="{{ UserProfil.nom }}" required></div>
      </div>
      <div class="row justify-content-md-center p-2">
        <div class="col-md-4">Adresse mail<input type="text" name="mail" class="form-control" aria-label="Adresse mail" value="{{ UserProfil.mail }}" required></div>
        <div class="col-md-4">Numéro de téléphone<input type="tel" name="phone" class="form-control" aria-label="Numéro de téléphone" value="{{ UserProfil.tel }}" required></div>
    </div>
    <div class="row justify-content-md-end p-2">
              <div class="col-md-3 "><button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false">Suivant</button></div>
            </div>
  </div>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" data-acc-step>
       <span class="badge rounded-pill text-bg-primary " data-acc-step>2</span> <h5 class="ms-3 mb-0">Adresse</h5>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        
          <div class="container">
            <div class="row justify-content-md-center p-2">
              <div class="col-md-4">Rue<input type="text" name="street" class="form-control" aria-label="Rue" value="{{ UserProfil.Rue }}" required></div>
              <div class="col-md-4">Code postal<input type="text" name="CP" class="form-control" aria-label="Code postal" value="{{ UserProfil.CP }}" required></div>
            </div>
            <div class="row justify-content-md-center p-2">
              <div class="col-md-4">Ville<input type="text" name="city" class="form-control" aria-label="Ville" value="{{ UserProfil.ville }}" required></div>
              <div class="col-md-4">Pays<input type="text" name="country" class="form-control" aria-label="Pays" value="{{ UserProfil.pays }}" required></div>
            </div>

            <div class="row justify-content-md-center p-2">
              <div class="col-md-5 justify-content-md-start"><button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false">Précédent</button></div>
              <div class="col-md-3 text-end"><button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false">Suivant</button></div>
            </div>
            
          </div>
          {% endfor %}
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree" data-acc-step>
      <span class="badge rounded-pill text-bg-primary " data-acc-step>3</span> <h5 class="ms-3 mb-0">Paiement</h5>
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
         <div class="container p-2">
      <div class="row justify-content-md-center p-2">
        <div class="col-md-8">Carte de crédit<input type="text" class="form-control" aria-label="creditcard" ></div>
      </div>
      <div class="row justify-content-md-center p-2">
        <div class="col-md-4">Date d'expiration<input type="text" class="form-control" aria-label="Expiry"></div>
        <div class="col-md-4">CVV<input type="text" class="form-control" aria-label="CVV"></div>
      </div>
      <div class="row justify-content-md-center p-2">
        <div class="col-md-5 justify-content-md-start"><button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false">Précédent</button></div>
        <div class="col-md-3 text-end"><button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false">Suivant</button></div>
      </div>
    </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour" data-acc-step>
      <span class="badge rounded-pill text-bg-primary " data-acc-step>3</span> <h5 class="ms-3 mb-0">Validation</h5>
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
         <div class="container p-2">
      <div class="row justify-content-md-center p-2">
        <div class="col-md-8">Montant total : {{ Mtotal }} euros</div>
      </div>
      <div class="row justify-content-md-center p-2">
        <div class="col-md-4">Nombre d'article : {{ NBarticle }}</div>
        <div class="col-md-4">Nombre de plante : {{ NBplante }}</div>
      </div>
      <div class="row justify-content-md-center p-2">
        <div class="col-md-5 justify-content-md-start"><button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false">Précédent</button></div>
        <div class="col-md-3 text-end"><button class="btn btn-primary">Payer</button></div>
      </div>
    </div>
    </div>
  </div>
</div>

</form>
</div>
{% endblock %}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}
<div class="jumbotron text-center shadow" style=" padding: 2rem 1rem; margin-bottom: 2rem; background-color: #e9ecef; border-radius: .3rem;">
  <div class="container mt-4">
    <h2>Panier</h2>
  </div>
</div>

<div class="container mt-4">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nom de l'article</th>
        <th>Quantité</th>
        <th>Prix à l'unité</th>
        <th>Prix total</th>
        <th class="text-center">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for plants, PanierPlants in PanierPlants %}
      <tr>
      <td><a href="{{ path('catalogue.show', {slug: PanierPlants.plants.slug, id: PanierPlants.plants.id}) }}">{{ PanierPlants.plants.title }}</a></td>
          <td><p>{{ PanierPlants.qt }}</p></td>
          <td>{{ PanierPlants.plants.price }} euros</td>
          <td>{{ PanierPlants.qt * PanierPlants.plants.price }} euros</td>
          <td class="text-center">
              <form method="post" action="{{ path('panier.delete', {id: PanierPlants.plants.id}) }}" style="display: inline-block">
                  <input type="hidden" name="_method" value="DELETE">
                  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ PanierPlants.plants.id) }}">
                  <button class="btn btn-danger ">Supprimer</button>
              </form>
          </td>
      </tr>
      {% endfor %}
      <tr>
      <td></td>
          <td></td>
          <td></td>
          <td>{{ Mtotal }} euros</td>
          <td class="text-center">
        
          </td>
      </tr>
    </tbody>
  </table>



  {% if PanierPlants != NULL %}
  <form method="get" action="{{ path('panier.confirm') }}" >
  <container class="mt-5 p-3 d-flex justify-content-center">
      <button class="btn btn-primary">Commander</button>
  </container>
  </form>
  {% else %}
  <p class="mt-3 text-center"> Veuillez ajouter des articles à votre panier.</p>
  <container class="mt-5 p-3 d-flex justify-content-center">
      <button class="btn btn-primary disabled">Commander</button>
  </container>

{% endif %} 




{% endblock %}