src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pays;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $CP;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Rue;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Status;

    /**
     * @ORM\Column(type="float")
     */
    private $MTotal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tel;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): self
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getCP(): ?string
    {
        return $this->CP;
    }

    public function setCP(string $CP): self
    {
        $this->CP = $CP;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->Rue;
    }

    public function setRue(string $Rue): self
    {
        $this->Rue = $Rue;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->Status;
    }

    public function setStatus(bool $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getMTotal(): ?float
    {
        return $this->MTotal;
    }

    public function setMTotal(float $MTotal): self
    {
        $this->MTotal = $MTotal;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getCreatedAt(): ?string
    {
        return date_format($this->created_at, "j/m/o - H:i:s");
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

templates/profil/_form.html.twig
{{ form_start(form) }}
             <div class="row justify-content-md-center p-2">
              <div class="col-md-4">{{ form_row(form.Rue)}}</div>
              <div class="col-md-4">{{ form_row(form.CP)}}</div>
            </div>
            <div class="row justify-content-md-center p-2">
              <div class="col-md-4">{{ form_row(form.Pays)}}</div>
              <div class="col-md-4">{{ form_row(form.Ville)}}</div>
            </div>
            <div class="row justify-content-md-center p-2 mt-3">
              <div class="col-md-4 text-start"><button class="btn btn-outline-secondary " href="{{ path('profil.index') }}">Annuler</button></div>
              <div class="col-md-4 text-end"><button class="btn btn-primary ">{{ button|default('Enregistrer') }}</button></div>
              
            </div>
{{ form_end(form) }}

           

templates/profil/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}

   
        <div class="jumbotron text-center shadow" style=" padding: 2rem 1rem; margin-bottom: 2rem; background-color: #e9ecef; border-radius: .3rem;">
<div class="container mt-4">

    <h2>Modifier votre adresse de livraison</h2>
</div>
</div>
    <div class="container mt-4">
        {{ include('profil/_form.html.twig', {button: 'Editer'}) }}
        
    </div>
   
       

{% endblock %}

templates/profil/index.html.twig
{% extends "base.html.twig" %}

{% block title 'Gérer les objets' %}

{% block body %}
<div class="jumbotron text-center shadow" style=" padding: 2rem 1rem; margin-bottom: 2rem; background-color: #e9ecef; border-radius: .3rem;">
<div class="container mt-4">

    <h2>Profil</h2>
</div>
</div>
<div class="container mt-4">

    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
        {{ message }}
    </div>
    {% endfor %}


</div>

<div class="container">
    {{ form_start(form) }}
    
            <div class="row justify-content-md-center p-2">
              <div class="col-md-9"><h4>Information personnelle</h4></div>
            </div>
             <div class="row justify-content-md-center p-2">
              <div class="col-md-4">{{ form_row(form.prenom)}}</div>
              <div class="col-md-4">{{ form_row(form.nom)}}</div>
            </div>
            <div class="row justify-content-md-center p-2">
              <div class="col-md-4">{{ form_row(form.mail)}}</div>
              <div class="col-md-4">{{ form_row(form.tel)}}</div>
            </div>
            <div class="row justify-content-md-center p-2 mt-3">
              <div class="col-md-4 text-start"></div>
              <div class="col-md-4 text-end"><button class="btn btn-primary" type="submit">Enregistrer</button></div>
            </div>

            <div class="row justify-content-md-center p-2">
              <div class="col-md-9"><h4>Adresse de livraison</h4></div>
            </div>
             <div class="row justify-content-md-center p-2">
              <div class="col-md-4">{{ form_row(form.Rue)}}</div>
              <div class="col-md-4">{{ form_row(form.CP)}}</div>
            </div>
            <div class="row justify-content-md-center p-2">
              <div class="col-md-4">{{ form_row(form.Pays)}}</div>
              <div class="col-md-4">{{ form_row(form.Ville)}}</div>
            </div>
            <div class="row justify-content-md-center p-2 mt-3">
              <div class="col-md-4 text-start"></div>
              <div class="col-md-4 text-end"><button class="btn btn-primary" type="submit">Enregistrer</button></div>
            </div>
{{ form_end(form) }}
</div>

{% endblock %}

templates/profil/new.html.twig
{% extends 'base.html.twig' %}
{% block body %}

   
        <div class="jumbotron text-center shadow" style=" padding: 2rem 1rem; margin-bottom: 2rem; background-color: #e9ecef; border-radius: .3rem;">
<div class="container mt-4">

    <h2>Ajouter une adresse de livraison</h2>
</div>
</div>
 <div class="container mt-4">
        <h2>{{ app.user.id }}</h2>
        {{ form_start(form) }}
            <div class="row">
                <div class="col-md-4">{{ form_row(form.Rue)}}</div>
            </div>
            <div class="row">
                <div class="col-md-4">{{ form_row(form.CP)}}</div>
            </div>
            <div class="row">
                <div class="col-md-4">{{ form_row(form.Pays)}}</div>
            </div>
            <div class="row">
                <div class="col-md-4">{{ form_row(form.Ville)}}</div>
            </div>
            <div class="row">
                <div class="col-md-4">{{ form_widget(form.user, {'value' : app.user.id ~ ""}) }}</div>
            </div>
            <button class="btn btn-primary mt-4">{{ button|default('Enregistrer') }}</button>
        {{ form_end(form) }}
        <div>
            <a href="{{ path('profil.index') }}" class="mt-3 btn btn-outline-secondary ">Annuler</a>
        </div>
    </div>


{% endblock %}